#ifndef MACROS_H
#define MACROS_H

#define MOTOR_CONTROL_PIN 26
#define PRESSURE_REFERENCE 25
#define PROPORTIONAL_VALVE 14

#define ADC_REFERENCE_VOLTAGE 3280

#define DAC_RESOLUTION 255 

#define SENSOR_VS           5000
#define SENSOR_REFERENCE    SENSOR_VS 
#define SENSOR_OFFSET       4600

#define FILTERING_COFFICIENT 0.93

#define PUMP_ON         255
#define PUMP_OFF        0
#define PUMP_CONTROL    150


#define _3300MV_CONVERSION_FACTOR 0.701

#define SAMPLING_TIME 5
#define SAMPLING_DURATION 1000

#define DEFAULT_FULLCAPREP 3000
#define BATTERY_CAPACITY   15000

#define FULLCAPREP_REG  0x10
#define REPSOC_REG      0x06

#endif