#ifndef MACROS_H
#define MACROS_H

#define _12V_ENABLE 27
#define _5V_ENABLE 14
#define MOTOR_CONTROL_PIN 25
#define PRESSURE_REFERENCE 26
#define PROPORTIONAL_VALVE 1
#define I2C_NUM       1       
#define SDA_PIN       21        
#define SCL_PIN       22
#define SWITCH_PIN    13

#define ADC_REFERENCE_VOLTAGE 3300
#define ADS1115_15_BIT_RESOLUTION  32767

#define DAC_RESOLUTION 255 

#define SENSOR_VS           5000
#define SENSOR_REFERENCE    SENSOR_VS 
#define SENSOR_OFFSET       4600

#define FILTERING_COFFICIENT 0.93

#define PUMP_ON         255
#define PUMP_OFF        0
#define PUMP_CONTROL    150

#define WEIGHTAGE 0.35f

#define _3300MV_CONVERSION_FACTOR 0.701

#define SAMPLING_TIME 4
#define SAMPLING_DURATION 1000
#define SAMPLES_PS (1000 / SAMPLING_TIME)

#define DEFAULT_FULLCAPREP 1500
#define BATTERY_CAPACITY   7500

#define FULLCAPREP_REG  0x10
#define REPSOC_REG      0x06
#define CURRENT        0X0A

#endif